const content = {
  "Diversification": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "",
    toc10: "",
    paragraph10: "",
  },
  "Allocations": {
    header1: "this is changed",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Rate of Return": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "IRR": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "ROE": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "PV": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "NPV": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Liabilities": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Short-Term Liabilities": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Long-Term Liabilities": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Assets": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Short-Term Assets": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Long-Term Assets": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Equity": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Free Cash Flow": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Net Income": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Revenue": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "EBIT": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Operating Cash Flow": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Investing Cash Flow": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Financing Cash Flow": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "What are your Ratios?": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Strategy and Ideas": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Income Estimator": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Portfolio Management": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Webcasts": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Events": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "R^2": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "PnL": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Debt/Equity": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "EPS": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "ROE": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "ROA": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Margins": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "Current Ratio": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  },
  "FCF Margin": {
    header1: "anus",
    toc1: "ass",
    paragraph1: "This is the content for Page 1",
    header2: "anus",
    toc2: "ass",
    paragraph2: "This is the content for Page 1",
    header3: "problamus",
    toc3: "ass",
    paragraph3: "This is the content for Page 1",
    header4: "Divefication",
    toc4: "ass",
    paragraph4: "This is the content for Page 1",
    header5: "Divefication",
    toc5: "ass",
    paragraph5: "This is the content for Page 1",
    header6: "Divefication",
    toc6: "ass",
    paragraph6: "This is the content for Page 1",
    header7: "Divefication",
    toc7: "ass",
    paragraph7: "This is the content for Page 1",
    header8: "Divefication",
    toc8: "ass",
    paragraph8: "This is the content for Page 1",
    header9: "Divefication",
    toc9: "ass",
    paragraph9: "This is the content for Page 1",
    header10: "Divefication",
    toc10: "ass",
    paragraph10: "This is the content for Page 1",
  }
  
};
